config/routes.rb
Dc1::Application.routes.draw do

  resources :addresses

  resources :schemes

  resources :entities

  resources :stakeholders

  resources :occasions

  resources :when_dates

  resources :webcrawls

  root to: 'static_pages#home'

  match '/about',    to: 'static_pages#about'
  
  resources :documents

  resources :standards

  resources :countries

  resources :projects

end

app/models/scheme.rb
class Scheme < ActiveRecord::Base
  attr_accessible :desc, :project_id, :standard_id
  belongs_to :project
  belongs_to :standard

  has_many :occasions, :as => :occasionable
  accepts_nested_attributes_for :occasions

  has_many :when_dates, :through => :occasions, :as => :occasionable, :source => :occasionable, :source_type => 'WhenDate'
end

app/controllers/schemes_controller.rb
class SchemesController < ApplicationController
  # GET /schemes
  # GET /schemes.json
  def index
    @schemes = Scheme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schemes }
    end
  end

  # GET /schemes/1
  # GET /schemes/1.json
  def show
    @scheme = Scheme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scheme }
    end
  end

  # GET /schemes/new
  # GET /schemes/new.json
  def new
    @scheme = Scheme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scheme }
    end
  end

  # GET /schemes/1/edit
  def edit
    @scheme = Scheme.find(params[:id])
  end

  # POST /schemes
  # POST /schemes.json
  def create
    @scheme = Scheme.new(params[:scheme])

    respond_to do |format|
      if @scheme.save
        format.html { redirect_to @scheme, notice: 'Scheme was successfully created.' }
        format.json { render json: @scheme, status: :created, location: @scheme }
      else
        format.html { render action: "new" }
        format.json { render json: @scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schemes/1
  # PUT /schemes/1.json
  def update
    @scheme = Scheme.find(params[:id])

    respond_to do |format|
      if @scheme.update_attributes(params[:scheme])
        format.html { redirect_to @scheme, notice: 'Scheme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schemes/1
  # DELETE /schemes/1.json
  def destroy
    @scheme = Scheme.find(params[:id])
    @scheme.destroy

    respond_to do |format|
      format.html { redirect_to schemes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schemes_helper.rb
module SchemesHelper
end

app/views/schemes/_form.html.erb
<%= form_for(@scheme) do |f| %>
  <% if @scheme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scheme.errors.count, "error") %> prohibited this scheme from being saved:</h2>

      <ul>
      <% @scheme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schemes/edit.html.erb
<h1>Editing scheme</h1>

<%= render 'form' %>

<%= link_to 'Show', @scheme %> |
<%= link_to 'Back', schemes_path %>

app/views/schemes/index.html.erb
<h1>Listing schemes</h1>

<table>
  <tr>
    
    <th>Standard</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schemes.each do |scheme| %>
  <tr>
    
    <td><%= scheme.standard_id %></td>
    <td><%= scheme.project_id %></td>
    <td><%= link_to 'Show', scheme %></td>
    <td><%= link_to 'Edit', edit_scheme_path(scheme) %></td>
    <td><%= link_to 'Destroy', scheme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scheme', new_scheme_path %>

app/views/schemes/new.html.erb
<h1>New scheme</h1>

<%= render 'form' %>

<%= link_to 'Back', schemes_path %>

app/views/schemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @scheme.desc %>
</p>


<%= link_to 'Edit', edit_scheme_path(@scheme) %> |
<%= link_to 'Back', schemes_path %>