config/routes.rb
Dc1::Application.routes.draw do

  resources :addresses

  resources :schemes

  resources :entities

  resources :stakeholders

  resources :occasions

  resources :when_dates

  resources :webcrawls

  root to: 'static_pages#home'

  match '/about',    to: 'static_pages#about'
  
  resources :documents

  resources :standards

  resources :countries

  resources :projects

end

app/models/entity.rb
class Entity < ActiveRecord::Base
  attr_accessible :title, :short_title

  has_many :addresses, :as => :addressable
  accepts_nested_attributes_for :addresses
  
  has_many :documents, :through => :occasions, :source => :occasionable, :source_type => "Document"
  has_many :standards, :through => :occasions, :source => :occasionable, :source_type => "Standard"
  has_many :schemes, :through => :occasions, :source => :occasionable, :source_type => "Scheme"

  has_many :occasions, :inverse_of => :when_date
  has_many :when_dates, :through => :occasions

  has_many :stakeholders, :inverse_of => :project
  has_many :projects, :through => :stakeholders
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  helper_method :sort_column, :sort_direction
  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entities }
    end
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
    @entity = Entity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entity }
    end
  end

  # GET /entities/new
  # GET /entities/new.json
  def new
    @entity = Entity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entity }
    end
  end

  # GET /entities/1/edit
  def edit
    @entity = Entity.find(params[:id])
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(params[:entity])

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render json: @entity, status: :created, location: @entity }
      else
        format.html { render action: "new" }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entities/1
  # PUT /entities/1.json
  def update
    @entity = Entity.find(params[:id])

    respond_to do |format|
      if @entity.update_attributes(params[:entity])
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity = Entity.find(params[:id])
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url }
      format.json { head :no_content }
    end
  end
  private

  def sort_column
    Entity.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= form_for(@entity) do |f| %>
  <% if @entity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
      <% @entity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :short_title %><br />
    <%= f.text_field :short_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @entity, :class => 'btn btn-mini'%> |
<%= link_to 'Back', entities_path, :class => 'btn btn-mini'%>

app/views/entities/index.html.erb
(<%= @entities.count %>, Rendered in <%= sprintf('%.3f', (Time.now.usec - @start_time).abs / 1000000.0) %> seconds)

<%= will_paginate @entities, :previous_label => h("<"), :next_label => h(">"), :class => "pagination pagination-mini text-center" %>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>
        <label class="checkbox">
          <input type="checkbox" value="">
        </label>
      </th>
      <th><small>Title</small></th>
      <th><small>Short title</small></th>
      <th><small>HQ country</small></th>
      <th><small>No. of projects</small></th>
      <th></th>
      
      <th></th>
    </tr>
  </thead>
  <tbody>

<% @entities.each do |entity| %>
  <tr>
    <td>
      <label class="checkbox">
        <input type="checkbox" value="">
      </label>
    </td>
    <td><%= link_to entity.title, entity %></td>
    <td><%= entity.short_title %></td>
    <td>
      <% entity.addresses.uniq.each do |a| %>
        <% if a.country.name == "United Kingdom of Great Britain and Northern Ireland" then %>
          <%= "UK" %><br />
        <% elsif a.country.name == "United States of America" %>
          <%= "USA" %><br />
        <% elsif a.country.name == "Republic of Korea" %>
          <%= "Korea" %><br />
        <% else %>
          <%= a.country.name %><br />
        <% end %>
      <% end %>
    </td>
    <td><%= entity.projects.count %></td>
    <td><%= link_to 'Edit', edit_entity_path(entity), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini' %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= will_paginate @entities, :previous_label => h("<"), :next_label => h(">"), :class => "pagination pagination-mini text-center" %>

<%= link_to 'New entity', new_entity_path %>

<% content_for :title do %>Entities<% end %>
<% content_for :description do %>My Description<% end %>

app/views/entities/new.html.erb
<h1>New entity</h1>

<%= render 'form' %>

<%= link_to 'Back', entities_path %>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Title:</b>
	<%= @entity.title %>
</p>

<p>
	<b>ID:</b>
	<%= @entity.id %>
</p>

<% if @entity.short_title %>
<p>
	<b>Short title:</b>
	<%= @entity.short_title %>
</p>
<% end %>
<p>
	<b>Projects:</b> <%= total = @entity.projects.count(:project_id, :distinct => true) %>
	<div class="row">
	
	<% @entity.projects.uniq.each_with_index do |p, i| %> 
		<% if p.refno %>
			<%= "<div class='span3' >".html_safe %>
				<small><%= i+1 %>. 
				<% if @entity.stakeholders.find_by_project_id(p.id).entity_role == "val_doe" then %>
					<% role = "Validator" %>
				<% elsif @entity.stakeholders.find_by_project_id(p.id).entity_role == "ver_doe" then %>
					<% role = "Verifier" %>
				<% elsif @entity.stakeholders.find_by_project_id(p.id).entity_role == "host_pp" then %>
					<% role = "Participant" %>
				<% elsif @entity.stakeholders.find_by_project_id(p.id).entity_role == "a1_pp" then %>
					<% role = "Participant" %>
				<% end %>
				<%= link_to p.standards.first.short_name + p.refno + " (" + role + ")", project_path(p) %>, </small>
			<%= "</div>".html_safe %>
		<% else %>
			<%= "None" %>
		<% end %>
	<% end %>
	</div>
</p>

<p>
	<b>Company's address:</b>
	<% @entity.addresses.each do |a| %>
		<%= a.country.name %><br />
	<% end %>
</p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%= link_to 'Back', stakeholders_path %>

<% content_for :title do %>Entity | <%= @entity.short_title || @entity.title %><% end %>
<% content_for :description do %>My Description<% end %>