config/routes.rb
Dc1::Application.routes.draw do

  resources :addresses

  resources :schemes

  resources :entities

  resources :stakeholders

  resources :occasions

  resources :when_dates

  resources :webcrawls

  root to: 'static_pages#home'

  match '/about',    to: 'static_pages#about'
  
  resources :documents

  resources :standards

  resources :countries

  resources :projects

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :link, :version, :short_title, :title, :process_type, :project_id
  belongs_to :project
  
  has_many :occasions, :as => :occasionable
  accepts_nested_attributes_for :occasions

  has_many :when_dates, :through => :occasions, :as => :occasionable, :source => :occasionable, :source_type => 'WhenDate'
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  helper_method :sort_column, :sort_direction
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.includes(:when_dates).order(sort_column + " " + sort_direction).page(params[:page]).per_page(30)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

private

  def sort_column
    Document.includes(:when_dates, :occasions).column_names.include?(params[:sort]) ? params[:sort] : "when_dates.date"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end


end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for @document, :html => { :class => 'form-horizontal'} do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    Document title
    <%= f.text_area :title %>
  </div>
  <br />
  <% @document.occasions.each do |o| %>
  <div>
    <%= o.description %>
    <% @when_date = WhenDate.find_by_id(o.when_date_id) %>
    <%= render 'when_dates/form' %>
  </div>
  <br />
  <% end %>
  <br />
  <div>  
    <%= f.submit nil, :class => 'btn btn-primary' %> |
    <%= link_to 'Cancel', project_path %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
(<%= @documents.count %>)
<%= will_paginate @documents, :previous_label => h("<"), :next_label => h(">"), :class => "pagination pagination-mini text-center" %><br />
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th><small><%= sortable "title" %></small></th>
      <th><small><%= sortable "short_title" %></small></th>
      <th><small><%= sortable "process_type", "Process" %></small></th>
      <th></th>
      <th><small><%= sortable "when_dates.date", "Upload date" %></small></th>
      <th><small>Standard</small></th>
      <th><small><%= sortable "project_id", "Project ID" %></small></th>
      <th></th>
    </tr>
</thead>
<tbody>
<% @documents.each do |document| %>
  <tr>
    <td><%= link_to document.title, document.link %></td>
    <td><%= link_to document.short_title, document.link %></td>
    <td><%= document.process_type %></td>
    <td>
      <% document.occasions.each do |o| %>
        <% if o.description =~ /issue/i %>
          <td><%= WhenDate.find(o.when_date_id).date.localtime.to_formatted_s(:just_date) %></td>
        <% elsif o.description =~ /upload/i && WhenDate.find(o.when_date_id)%>
          <%= WhenDate.find(o.when_date_id).date.localtime.to_formatted_s(:just_date) %>
        <% elsif %>
          <%= "?" %>
        <% end %>
      <% end %>
    </td>
    <td><%= document.project.standards.first.short_name %></td>
    <td><%= document.project_id %></td>
    <td><%= link_to 'Show', document, :class => 'btn btn-mini' %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= will_paginate @documents, :previous_label => h("<"), :next_label => h(">"), :class => "pagination pagination-mini text-center" %>
<% content_for :title do %>Documents<% end %>
<% content_for :description do %>My Description<% end %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p>
  <b>Title:</b>
  <%= @document.title %>
</p>

<p>
  <b>Link:</b>
  <%= @document.link %>
</p>
<% @document.occasions.each do |o| %>
<p>
  <b>Issue date:</b>
  <% if o.description =~ /issue/i %>
  <%= WhenDate.find(o.when_date_id).date_string %>
</p>
<p>
  <b>Upload date:</b>
  <% elsif o.description =~ /upload/i %>
  <td><%= WhenDate.find(o.when_date_id).date_string %>
<% else %>
	<%= "?" %>
  </td>
<% end %>
<% end %>
</p>

<p>
  <b>Project:</b>
  <%= @document.project_id %>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>