config/routes.rb
Dc1::Application.routes.draw do

  resources :addresses

  resources :schemes

  resources :entities

  resources :stakeholders

  resources :occasions

  resources :when_dates

  resources :webcrawls

  root to: 'static_pages#home'

  match '/about',    to: 'static_pages#about'
  
  resources :documents

  resources :standards

  resources :countries

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :refno, :fee, :scale

  has_many :addresses, :as => :addressable
  accepts_nested_attributes_for :addresses

  # has_many :countries, :through => :stakeholders

  has_many :countries, :through => :addresses

  has_many :schemes, :inverse_of => :standard
  has_many :standards, :through => :schemes

  has_many :webcrawls

  has_many :occasions, :inverse_of => :when_date
  has_many :when_dates, :through => :occasions

  has_many :documents
  #has_many :documents, :through => :occasions, :source => :occasionable, :source_type => "Document"

  has_many :stakeholders, :inverse_of => :entity
  has_many :entities, :through => :stakeholders

  has_many :relationships, foreign_key: "main_proj_id", dependent: :destroy
  has_many :assoc_projects, through: :relationships, source: :assoc_proj 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
helper_method :sort_column, :sort_direction, :sort, :sort_by_country

  def index
    if params[:sort] == "c_name"
      @projects = sort_by_country
    else
      @projects = sort
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id], :include => :documents)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private

  def sort
    Project.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 30)
  end

  def sort_by_country
    Project.joins(:countries).select("projects.*, countries.name as c_name").order("c_name #{sort_direction}").paginate(:page => params[:page], :per_page => 30)
  end

  def sort_column
    Project.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Project title
    <%= f.text_area :title %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => 'btn btn-primary' %> |
    <%= link_to 'Cancel', project_path %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row-fluid">
	<div class="span9">
		<h4><%= @project.title %></h4>
	</div>
	<div class="span3">
		<%= render 'form' %>
	</div>
</div>
<% @project.documents.each do |d| %>
<div class="row-fluid"  style="margin-bottom: 10px">
	<div>
		<a data-toggle="collapse" data-target="#collapse<%= d.id %>" href="#collapse<%= d.id %>">
			<h5><%= d.title %> (<% if d.when_dates.first then %><%= d.when_dates.first.date %><% end %> )</h5>
		</a>
	</div>
	<div id="collapse<%= d.id %>" class="collapse">
		<div id="pdf">
			<object class="span9" type="application/pdf" data="<%= d.link+'#zoom=90&scrollbar=0&toolbar=0&navpanes=0' %>" id="pdf_content">
			<p class="lead">Can't display the document in your browser. Try <a href="<%= d.link %>">downloading</a> it.</p>
			</object>
			<div class="span3">
				<div>
					<% @document = d %>
					<%= render 'documents/form' %>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/projects/index.html.erb
<%= @projects.count %>, Rendered in <%= sprintf('%.3f', (Time.now.usec - @start_time).abs / 1000000.0) %> seconds

<%= will_paginate @projects, :previous_label => h("<"), :next_label => h(">"), :class => "pagination pagination-mini text-center" %>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>
        <label class="checkbox">
          <input type="checkbox" value="">
        </label>
      </th>
      <th><small>Standard</small></th>
      <th width="60px"><small><%= sortable "refno", "Ref №" %></small></th>
      <th width="600px"><small><%= sortable "title" %></small></th>
      <th><small>Docs</small></th>
      <th width="100px"><small><%= sortable "c_name", "Host country" %></small></th>
      <th><small><%= "Annex-I Party" %></small></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
<tbody>
<% @projects.each do |p| %>
  <tr>
    <td>
      <label class="checkbox">
        <input type="checkbox" value="">
      </label>
    </td>
    <td>
      <% if p.standards.first.nil? then %> 
        <%= "Unknown" %>
      <% else %>
        <%= p.standards.first.short_name %>
      <% end %>
    </td>
    <td valign="top"><%= link_to p.refno, p.webcrawls.first.url if !p.webcrawls.first.nil? %></td>
    <td valign="top"><small><%= link_to p.title, project_path(p) %></small></td>
    <td><%= p.documents.count %></td>
    <td>
      <% p.countries.each do |c|%>
        <%= c.name %>
      <% end %>
    </td>
   <td>
      <% if c = p.stakeholders.where(:country_role => "Investor") then %>
        <% c.map(&:country_id).uniq.each do |s| %>
          <% Country.where(:id => s).each do |y| %>
            <% if y.name == "United Kingdom of Great Britain and Northern Ireland" then %>
              -&nbsp;<%= "UK" %><br />
            <% else %>
              -&nbsp;<%= y.name %><br />
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </td>
    <td><%= link_to 'Edit', edit_project_path(p), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', p, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini' %></td>
  </tr>
<% end %>
</tbody>
</table>

<%= will_paginate @projects, :previous_label => h("<"), :next_label => h(">"), :class => "pagination pagination-mini text-center" %>

<% content_for :title do %>Projects<% end %>
<% content_for :description do %>My Description<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<b>Title:</b>
	<%= @project.title %>
</p>
<p>
	<b>Reference number:</b>
	<%= @project.refno %>
</p>
<p>
	<b>Standard:</b>
	<%= @project.standards.first.name %>
</p>
<p>
	<b>Scale:</b>
	<% if !@project.scale.blank? %>
		<%= @project.scale %>
	<% else %>
		<%= "Unknown" %>
	<% end %>
</p>
<p>
	<b>Validating DOE:</b>
	<% @project.stakeholders.find_all_by_entity_role("val_doe").each do |e| %>
		<% if e.entity %>
			<%= e.entity.title %>
		<% else %>
			<%= "Unknown" %>
		<% end %>
	<% end %>
</p>
<p>
	<b>Verifying DOEs:</b>
	<% @project.stakeholders.find_all_by_entity_role("ver_doe").each do |e| %>
		<% if e.entity %>
			<%= e.entity.title %>
		<% else %>
			<%= "Unknown" %>
		<% end %>
	<% end %>
</p>
<p>
	<b>Host country:</b>
	<% if !@project.addresses.blank? then %>
		<% @project.addresses.each do |a| %>
			<%= a.country.name %>
		<% end %>
	<% else %>
		<%= "Unknown" %>
	<% end %>
	(<% @project.stakeholders.find_all_by_entity_role("host_pp").each do |e| %>
		<% if e.entity %>
			<%= link_to e.entity.title + ";", entity_path(e.entity) %>
		<% else %>
			<%= "Unknown" %>
		<% end %>
	<% end %>)
</p>

<p>
<b>Investor countries:</b>
<% if !@project.stakeholders.find_all_by_country_role("Investor").blank? %>
	<% @project.stakeholders.find_all_by_country_role("Investor").map(&:country_id).uniq.each do |s| %>
        <% if c = Country.find_by_id(s) then %>
	        <ul>
				<b><%= c.name %></b>
				(<% @project.stakeholders.find_all_by_entity_role_and_country_id("a1_pp", c.id).each do |e| %>
					<% if e.entity then%>
						<%= link_to e.entity.title + ";", entity_path(e.entity) %>
					<% else %>
						<%= "Unknown" %>
					<% end %>
				<% end %>)
			</ul>
		<% end %>
    <% end %>
<% else %>
	<%= "None" %>
<% end %>
</p>
<p>
	<b>Fee:</b>
	<% if !@project.fee.blank? %>
		$<%= @project.fee %>
	<% else %>
		<%= "Unknown" %>
	<% end %>
</p>

<p>
	<b>Documents:</b>
	<% @project.documents.each do |d| %>
		<ul><%= link_to d.title, d.link %>
		</ul>
	<% end %>
</p>


<%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-mini' %> |
<%= link_to 'Back', projects_path, :class => 'btn btn-mini' %>

<% content_for :title do %>Project <%= @project.standards.first.short_name + @project.refno %><% end %>
<% content_for :description do %>My Description<% end %>